### ISSUE TITLE
Support ansi colors

### ISSUE THREAD

**Issue by rickard-von-essen** [peco/peco#188]
Instead of filtering color codes it would be nice too keep them.

**Comment by deiga** [comment]
This would really be appreciated, currently I use coloured output for `ls` and it leaves ugly control characters in peco.

I'd love to make a PR, but I really don't know go enough to achieve this with any ease.

**Comment by Komosa** [comment]
Even if we assume that only text will be colored (not background), we must decide how to mark matching part of colored input string.

Maybe another color of bg?

Also, linear computation cost will be ok?

**Comment by rcoedo** [comment]
+1 for passing colors

**Comment by slavaGanzin** [comment]
Why code from fzf can't be ported here?
