### ISSUE TITLE
Slugginsh behaviour on "large" terminals

### ISSUE THREAD

**Issue by cipriancraciun** [peco/peco#217]
For some reason having a large terminal (in my case ~64x190) makes `peco` behave quite slugish when browsing up-and-down through the list.  (For example if keeping `down` pressed for a few seconds, and releasing it, it takes `peco` a few more second to finally "process" these key presses.)

For what I see this is not linked to the size of the buffer (I tried with `/etc/services`, about 11k lines, and also with `tail -n 100 /etc/services` and it behaves identically).

(Perhaps you are redrawing the entire screen each time?)

**Comment by victorhooi** [comment]
I don't know if this is related, or a separate issue, but `peco` seems to be having issues with large files:

I'm trying to use `peco` to analyse a MongoDB logfile. The logfile is 173 MB.

When I try to filter on a word that I know occurs many times in the file, `peco` only seems to display a few results.

For example:
```
grep query mongodb.log  | wc
  194641 14989000 132633089
```
And `peco` will show:

```
QUERY> query                                                                                                                                                                                                                                                                                                                                            IgnoreCase [3 (1/1)]
2014-12-12T10:10:35.078-0500 [conn1] assertion 13435 not master and slaveOk=false ns:test.system.namespaces query:{}
2014-12-12T10:23:14.236-0500 [conn1] assertion 13435 not master and slaveOk=false ns:admin.system.namespaces query:{}
2014-12-12T11:00:15.371-0500 [conn1] insert mydb.collection1 query: { _id: 0.0, x: 25.0, y: 0.0, z: "foo" } ninserted:1 keyUpdates:0 numYields:0 locks(micros) w:167305 166ms
```

Then, after a while (10-15 seconds later), it will slowly start to show other results.

For other keywords, it just seems to display nothing, even after 1-2 minutes.

It seems like a cool tool, and I'd love to use it, but I'm not really sure if it's just not capable of handling those size files, or if it's a screen redrawing issue.

**Comment by lestrrat** [comment]
@victorhooi In your case I think the dataset is just too big. peco isn't exactly a speed monster (yet), as I really never intended to use it against a huge dataset when I initially wrote it.

So yeah, I hear you, and I will start thinking about users like you in my next batch of changes so that in the future peco can be used in your usecase, but for the moment, sorry, peco just wasn't made for that purpose

**Comment by lestrrat** [comment]
@cipriancraciun out of curiosity, does the latest peco fix your issue? I forgot to mention it here, but I implemented a display cache of sorts.
