### ISSUE TITLE
inverse matches (as in `grep -v`)

### ISSUE THREAD

**Issue by dAnjou** [peco/peco#220]
Hi, is there a simple way to invert matches like `grep -v` does?

If not I could imagine to have inverse matchers additional to the existing ones.

**Comment by syohex** [comment]
FYI Inverse match can be implemented as custom matcher.
For example(You can write custom matcher in your favorite programming language)

```perl
#!/usr/bin/env perl
use strict;
use warnings;

my $query = shift;
my @queries = split /\s/, $query;

while (my $line = <STDIN>) {
    my $match = 0;
    for my $q (@queries) {
        if ($line =~ m{$q}) {
            $match = 1;
            last;
        }
    }
    print $line unless $match;
}
```

Add above matcher to your configuration file(such as `~/.peco/config.json`).

```json
{
    "CustomMatcher": {
	"InvertMatch": [
		"/somepath/reverse.pl",
		"$QUERY"
	]
    }
}
```

Here is screencast

![screencast inverse matcher](http://cdn-ak.f.st-hatena.com/images/fotolife/s/syohex/20141101/20141101231536.gif)

**Comment by dAnjou** [comment]
I figured but that would be much slower, right? Because it doesn't use concurrency.

**Comment by mattn** [comment]
> I figured but that would be much slower, right? Because it doesn't use concurrency.

Really?

https://github.com/peco/peco/blob/f69b17426977d12304d3b3d008aea549e3972e8b/matchers.go#L426-L444

**Comment by mattn** [comment]
Ah, as you said, it should read with bufio.Reader.

**Comment by dAnjou** [comment]
Thanks guys, I'm fine with closing this one.
