### ISSUE TITLE
Allow word wrap, or horizontal scrolling?

### ISSUE THREAD

**Issue by victorhooi** [peco/peco#222]
Is there any way we could either enable some kind of wrapping mode, and/or allow horizontal scrolling?

I'm using `peco` to analyse logfiles with some rather long loglines - and the pertinent content is at the end of the line (i.e. off to the right of the screen).

**Comment by lestrrat** [comment]
ATM no you can't.
Am I against such use case? no.
Am I going to fix it soon...? Well, I'm not really a UI guy, so ....maaaaaybe. I would say giving me pointers on existing code that implement this may help me somewhat.
