### ISSUE TITLE
Peco always returns EOF.

### ISSUE THREAD

**Issue by h17u** [peco/peco#223]
Hi,

I upgraded my MacOS X to Yosemite. After upgrading, peco can't work properly. Peco always returns EOF. I tried uninstall and install but peco returns same results. The following are the details.

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.10.1
BuildVersion:   14B25

$ peco --version
peco: v0.2.11

$ ls -al | peco
EOF

$ brew untap peco/peco && brew tap peco/peco
$ brew unlink peco && brew uninstall peco && brew install peco

$ ls -al | peco
EOF

**Comment by lestrrat** [comment]
I'm going to sound really dumb, but what do you mean by EOF...?
EOF to me is End Of File, and I have no clue what it means by "peco returns EOF".
I've also made sure to install peco 0.2.11, and I have no problems.

**Comment by h17u** [comment]
Hmm. I add more examples. Current directory has 3 files and ls -l command returns 3 rows. But peco returns EOF. Is this OK?

$ mkdir tmp & cd tmp
$ touch 01.txt
$ touch 02.txt
$ touch 03.txt

$ ls -l
total 0
-rw-rw-r-- 1 tommy staff 0 2015-02-04 17:52 01.txt
-rw-rw-r-- 1 tommy staff 0 2015-02-04 17:52 02.txt
-rw-rw-r-- 1 tommy staff 0 2015-02-04 17:52 03.txt

$ ls -l | peco
EOF

**Comment by lestrrat** [comment]
Again, I don't get it. What do you mean by EOF.
Is it *printing* EOF ? Is it *terminating* without any output?

**Comment by h17u** [comment]
It is printing EOF.

**Comment by lestrrat** [comment]
![peco-20150204](https://cloud.githubusercontent.com/assets/49281/6037897/b0e1844c-ac9b-11e4-9f76-3db41d89b065.gif)

Sadly ATM with the given hint I have no clue.

**Comment by syohex** [comment]
@h17u Is there empty config file, `~/.peco/config.json` or `~/.config/peco/config.json` ?

I can reproduce this issue with empty config file.

1. `rm ~/.peco/config.json`
2. `touch ~/.peco/config.json`
3. `ls -l | peco`

I got EOF.

**Comment by h17u** [comment]
OMG! I see. Thank you anyway.

**Comment by h17u** [comment]
Yes, I have empty config file. I move config file to backup directory temporarily, then peco works properly.
This is my mistake. Thanks for your help. :)

**Comment by lestrrat** [comment]
Thanks. But peco should survive an empty file. So reopening it so that we can work on a fix.

**Comment by lestrrat** [comment]
Note to self: In light of other people's comments, I think I'm just going to make the error message better and not allow empty config files
