### ISSUE TITLE
Matched highlight collapsed for ":\t" (colon + tab)

### ISSUE THREAD

**Issue by nobeans** [peco/peco#226]
```
$ echo -e "foo:\t1234\nbar:\t1234\nbaz\t1234\nbazz:  1234" | peco
```

```
QUERY>
foo:    1234
bar:    1234
baz 1234
bazz:  1234
```

```
QUERY> 3
foo:   34
bar:   34
baz 1234
bazz:  1234
```

```
QUERY> 4
foo:    4
bar:    4
baz 1234
bazz:  1234
```

**Comment by lestrrat** [comment]
Whoa. WTF.
Thanks for the report

**Comment by lestrrat** [comment]
@mattn It looks like this is the cause: https://github.com/peco/peco/blob/6f4d8559e25ef245a5979bf12f53871742a0cd69/layout.go#L69-L75

We control where we draw the next character in the [outer loop](https://github.com/peco/peco/blob/6f4d8559e25ef245a5979bf12f53871742a0cd69/layout.go#L343) but it doesn't match the expanded tab character count.

It looks like you put that tab expansion thing, @mattn I don't mind fixing it, but is removing the tab expansion an option? If not, I'll think of some other way.

**Comment by syohex** [comment]
```diff
diff --git a/layout.go b/layout.go
index aa223d1..d99a0aa 100644
--- a/layout.go
+++ b/layout.go
@@ -291,6 +291,24 @@ func NewListArea(ctx *Ctx, anchor VerticalAnchor, anchorOffset int, sortTopDown
 	}
 }
 
+func previousWidth(x int, s string) int {
+	width := 0
+	pos := x
+	for _, c := range []rune(s) {
+		var w int
+		if c == '\t' {
+			w = (4 - pos % 4)
+		} else {
+			w = runewidth.RuneWidth(c)
+		}
+
+		pos += w
+		width += w
+	}
+
+	return width
+}
+
 // Draw displays the ListArea on the screen
 func (l *ListArea) Draw(targets []Line, perPage int) {
 	currentPage := l.currentPage
@@ -335,12 +353,12 @@ func (l *ListArea) Draw(targets []Line, perPage int) {
 				if m[0] > index {
 					c := line[index:m[0]]
 					printScreen(prev, y, fgAttr, bgAttr, c, false)
-					prev += runewidth.StringWidth(c)
+					prev += previousWidth(prev, c)
 					index += len(c)
 				}
 				c := line[m[0]:m[1]]
 				printScreen(prev, y, l.config.Style.MatchedFG(), mergeAttribute(bgAttr, l.config.Style.MatchedBG()), c, true)
-				prev += runewidth.StringWidth(c)
+				prev += previousWidth(prev, c)
 				index += len(c)
 			}
 ```

#### original
![peco-test-orig](https://cloud.githubusercontent.com/assets/554281/6386752/146ede4c-bdc2-11e4-8983-b0b1dc599ebe.gif)


#### fixed version
![peco-test](https://cloud.githubusercontent.com/assets/554281/6386753/18242a38-bdc2-11e4-8f03-b43a64b1fc1c.gif)

**Comment by lestrrat** [comment]
@syohex あー、special purpose関数作っちゃうのか…そのほうがお手軽かな？　
僕はprintScreenで書いたバイト数を返すようにしようかと思っていた

**Comment by syohex** [comment]
そちらの方が良さそうです.

**Comment by lestrrat** [comment]
Done. I think it works.

**Comment by nobeans** [comment]
Great! It also works for me.
