### ISSUE TITLE
Doesn't highlight keyword in some cases

### ISSUE THREAD

**Issue by nobeans** [peco/peco#228]
```
$ echo -e "1234\n1 2 3 4" | peco
```

![peco](https://cloud.githubusercontent.com/assets/18579/6388122/5f5408bc-bdd9-11e4-86be-3dddc888b601.gif)

In the case of the order `1 2 3 4`, it works well. But in the case of `1 3 2 4`, number `2` isn't highlighted only in the line of `1234` without spaces.

**Comment by lestrrat** [comment]
This is caused by silly mangling of matched results in matchers.go
Currently thinking what the best approach is...

**Comment by mattn** [comment]
I'm thinking `1 2 3 4` should be handled as below:

```
^1\s*2\s*3\s*4$
```

**Comment by lestrrat** [comment]
@mattn That's okay if we're going to bump the major version or something. If you're talking about including this in the next minor release, let's not do that...

**Comment by mattn** [comment]
indeed. BTW, FYI: gof make pattern as i said in above: https://github.com/mattn/gof/blob/master/gof.go#L124-L128

**Comment by lestrrat** [comment]
Note to self: If we're going to do this, I want to be able to get the old behavior back via some sort of option

**Comment by lestrrat** [comment]
とりあえず 7ad8185で諸々直ってるはず。スピードは多少犠牲にした

**Comment by mattn** [comment]
お！

**Comment by syohex** [comment]
本題が直っていることは確認できました.

**Comment by mattn** [comment]
Me Too

**Comment by lestrrat** [comment]
もう一個だけ微調整したのでその結果待ち

**Comment by mattn** [comment]
先頭にマッチしなくなりましたね。
