### ISSUE TITLE
Japanese input → Delete → input again barfs terminal

### ISSUE THREAD

**Issue by lestrrat** [peco/peco#236]
See image. v0.2.11 exhibits this problem. I'm using ATOK on OS X

![peco-20150311-jp-bug](https://cloud.githubusercontent.com/assets/49281/6589246/508d1dda-c7e0-11e4-913a-1f21ef6e1f86.gif)

**Comment by mattn** [comment]
https://github.com/nsf/termbox-go/pull/69

**Comment by mattn** [comment]
are you still having this issue?
