### ISSUE TITLE
Output duplication

### ISSUE THREAD

**Issue by k0kubun** [peco/peco#245]
With peco 0.3.2, OSX 10.10.3

![](http://i.gyazo.com/17d2773f3875bebf75bb56d853a6d1fa.gif)

In this movie, input has only one k0kubun/dotfiles but output has double k0kubun/dotfiles.

**Comment by lestrrat** [comment]
なんかbrewのpeco壊れてないかなぁ… 手元のレポジトリからやると普通に動くんだけど…

**Comment by k0kubun** [comment]
issue立てるまでは再現率100%だったんですが、寝て起きたら再現しなくなったので、一旦クローズします、すみません
