### ISSUE TITLE
OpenBSD support?

### ISSUE THREAD

**Issue by jpeirce** [peco/peco#246]
`$ go build`
`# _/home/jack/src/peco`
`./tty_posix.go:13: undefined: syscall.TCGETS`
`$ go version`
`go version go1.4.1 openbsd/amd64`

[I see you fixed a similar issue for FreeBSD](https://github.com/peco/peco/issues/159), hoping you can do the same here!

thanks!

**Comment by mattn** [comment]
Could you please try following patch?
```diff
diff --git a/tty_bsd.go b/tty_bsd.go
index d9881ce..7f08b1b 100644
--- a/tty_bsd.go
+++ b/tty_bsd.go
@@ -1,4 +1,4 @@
-// +build darwin freebsd
+// +build darwin freebsd openbsd
 
 package peco
 
diff --git a/tty_posix.go b/tty_posix.go
index f0972dc..3d7da7b 100644
--- a/tty_posix.go
+++ b/tty_posix.go
@@ -1,4 +1,4 @@
-// +build !darwin,!windows,!freebsd
+// +build !darwin,!windows,!freebsd,!openbsd
 
 package peco
 
```

**Comment by jpeirce** [comment]
Yes that works, thank you very much!

**Comment by lestrrat** [comment]
@mattn thanks, will just patch it in master

**Comment by mattn** [comment]
@lestrrat do it plz
