### ISSUE TITLE
Select filter directly by single key, not toggle

### ISSUE THREAD

**Issue by yoshinari-nomura** [peco/peco#252]
Is there any way to bind a key to select a particular filter?

In most cases, `IgnoreCase` filter works for me, but occasionally, I need to use `MigemoFilter`.
In such case, *knocking ^R four times* is painful for me :)

Or, if I could toggle filters only among my prefer filters, that would be nice.

**Comment by syohex** [comment]
> Is there any way to bind a key to select a particular filter?

There is no way now.

**Comment by lestrrat** [comment]
Because the filters are (sort of) pluggable, it's kind of hard to hardcode a key to a filter.
Maybe we can have an action for `SelectFilterN` where N could be a number, and it would just select that filter?

**Comment by yoshinari-nomura** [comment]
Hi guys, thanks for the helpful suggestions.
>  Maybe we can have an action for SelectFilterN where N could be a number, and it would just select that filter?

Yes, this is the perfect solution to resolve my personal problem. But, on reconsidering the matter from the engineering point of view, I'm afraid you might feel it a little bit ad-hoc solution.

Instead, what if we can enumerate one's preferred filters in `config.json`?
We can remove unused default filters from the toggling-list.
In my case, I will have only two filters in the list, so, `^R` should be enough to me.

**Comment by lestrrat** [comment]
Well, I was thinking maybe:

```
Filters: [ "IgnoreCase", "Migemo" ],
CustomFilter: {
    "Migemo": { .... }
},
Keymap: {
    "C-R-1": "SelectFilter-1",
    "C-R-1": "SelectFilter-1"

}
```

hmmm, now I want to pass arguments to Keymap, but that's starting to sound like more trouble... let me think about it.

**Comment by yoshinari-nomura** [comment]
Thanks, I think we have the same picture.
I can understand introducing arguments needs fair amount of work.

I've come up with an another idea.
How about introduce `Filters` and `peco.BackToInitialFilter` ?
Utilizing these two, we can define `foo.SelectMigemo`.

```json
    "Filters": [ "IgnoreCase", "RegExp", "Migemo" ],
    "Action": {
        "foo.SelectMigemo": [
            "peco.BackToInitialFilter",
            "peco.RotateFilter",
            "peco.RotateFilter"
        ]
    }
```
Now, we can bind `foo.SelectMigemo` to any key we want.

**Comment by lestrrat** [comment]
That is clever :)
Unless somebody beats me to it, I'll probably write that patch.

**Comment by yoshinari-nomura** [comment]
Thank you so much
I wish I could, but I'm almost next to nothing about golang.

**Comment by lestrrat** [comment]
@yoshinari-nomura So I implemented `peco.BackToInitialFilter` 

I haven't implemented a way to choose which filters are available, so you would need to do this (4 rotates):

```
    "Action": {
        "foo.SelectMigemo": [
            "peco.BackToInitialFilter",
            "peco.RotateFilter",
            "peco.RotateFilter",
            "peco.RotateFilter",
            "peco.RotateFilter"
        ]
    },
```

If you know how to build peco, you can test it out, but otherwise please wait until others review my PR for a release.

**Comment by yoshinari-nomura** [comment]
Super fast!
I've tried `topic/issue-252`. Everything goes well as expected.

Please close this issue at any time you like.
Thank you again.
