### ISSUE TITLE
scroll & query -> no display

### ISSUE THREAD

**Issue by rubikitch** [peco/peco#260]
$ cat /proc/meminfo | peco

Then input RightArrow and "mem", got no results are displayed.
But show results by pressing an arrow key.

**Comment by mattn** [comment]
what do you mean `mem`? please explain how to reproduce, and description of your environments.

**Comment by syohex** [comment]
I suppose this issue is like this.

![output](https://cloud.githubusercontent.com/assets/554281/10126404/948cf4e4-65cc-11e5-8ea1-1508a9da6743.gif)

After inputing `mem`, there are only one page. But peco display second page.
And then `current page` is larger than `total page`, this is strange.

`peco` should be display first page when inputing something.

**Comment by lestrrat** [comment]
@syohex nrhd

**Comment by lestrrat** [comment]
I think I know where it is (I probably need to do something in layout.go to compare CurrentLineBuffer.Size() against current page position...) but probably will only have time to work on it later.

**Comment by mattn** [comment]
I guess it is difficul to fix this. for example
1. type RightAllow to move next page
2. type "mem"
3. type `<bs><bs><bs>`
what should be displayed? first page? second page?

**Comment by rubikitch** [comment]
Helm and Anything (Emacs Lisp programs) show first page in this case.
I think this is right behavior because query is changed.

**Comment by lestrrat** [comment]
Instead of moving to the first page regardless, I'd rather want peco to stay in the current location as much as possible. So if we were at line 3 on page 3, and we end up with 6 entries and 2 page, I want the highlighted line to be line 3 on page 2

**Comment by lestrrat** [comment]
how's this? fe1be27

**Comment by rubikitch** [comment]
OK! thank you very much.

**Comment by syohex** [comment]
It looks bug.

```
# I assume that `ps aux` outputs multiple page soutput
% ps aux | peco
```

`peco` always display first page except displaying last page.

I press right arrow key repeatedly. But peco displays only first page except last page.

![output](https://cloud.githubusercontent.com/assets/554281/10129370/41e7d20a-65f8-11e5-8550-6d1b103a8f63.gif)

**Comment by lestrrat** [comment]
It looks "like there is a" bug だと『バグが「あるみたい」』になります！

Okay, so I think this auto-paging behavior should only be done when we run a query, and I don't think I encoded it. will fix.

**Comment by lestrrat** [comment]
How about it now.

**Comment by syohex** [comment]
> How about it now.

Looks good.

BTW. There might be a similar bug. (This is not related to these changes).

1. Move cursor to line `L`
2. Input query and narrow the candidates(narrow from `N` to `M`)
3. If `L` is larger than `M`, active(highlighted) line is disappeared.

![output](https://cloud.githubusercontent.com/assets/554281/10130535/684eeeea-6604-11e5-934a-734678ad5ec9.gif)

**Comment by lestrrat** [comment]
@syohex fixed, I think.

**Comment by syohex** [comment]
Looks good for both issues. :+1:
