### ISSUE TITLE
hit-a-hint

### ISSUE THREAD

**Issue by lestrrat** [peco/peco#261]
http://twitter.com/rubikitch/status/648354947059204096

**Comment by syohex** [comment]
I confirmed `topic/issue-261` branch works. However I suppose it is difficult to use this feature for peco users without hint character(highlighted character of beginning of line) as below.

![example](https://camo.githubusercontent.com/d8a8d2610cfca12c629ce8400335da1169fa5688/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f333739373036322f323036323639362f63616535306433362d386339612d313165332d386463622d3366346238653966313634642e676966)

**Comment by lestrrat** [comment]
Yep. Agreed.
