### ISSUE TITLE
--initial-filter and --null

### ISSUE THREAD

**Issue by rubikitch** [peco/peco#272]
Combining --initial-filter and --null got wrong result.

```
#!/bin/zsh
cd /tmp
cat <<EOF > peco.bug.json
{
    "CustomFilter": {
        "grep": {
            "Cmd": "grep",
            "Args": ["$QUERY"]
        }
    }
}
EOF
echo "display\0real\n" > input.txt
# got real
peco --null --rcfile peco.bug.json --initial-filter grep input.txt
# got real
peco --null --query di input.txt
# BUG! got display
peco --null --rcfile peco.bug.json --initial-filter grep --query di input.txt
```

**Comment by syohex** [comment]
This is a known issue.

https://github.com/peco/peco/blob/master/filter.go#L513-L516

**Comment by lestrrat** [comment]
Ah this, yeah.... Maybe I need to rethink about the source abstraction a bit better, but at the time this was all I could come up with

**Comment by lestrrat** [comment]
@rubikitch it took me forever, but I think this issue should be fixed with #312

**Comment by lestrrat** [comment]
oops, I think I have to work out the spec a bit more...

**Comment by lestrrat** [comment]
Okay, I changed CustomFilter to carry a `ReturnsLineID` field.
In this case, you receive `display_line\0line_id` fed into your custom filter, and your custom filter should return `line_id` when there's a match.

Here's an example filter:
```perl
#!perl
use strict;

my $query = shift @ARGV;
while (<>) {
    my ($txt, $id) = split(/\0/);
    if ($txt =~ /$query/) {
        print "$id\n";
    }
}
```

and here's the rcfile:

```json
{
    "CustomFilter": {
        "myfilter": {
            "Cmd": "perl",
            "Args": ["hoge.pl", "$QUERY"],
            "ReturnsLineID": true
        }
    }
}
```
