### ISSUE TITLE
Nothing selected when using --initial-filter

### ISSUE THREAD

**Issue by rubikitch** [peco/peco#273]
Nothing is selected when typing fast when using --initial-filter.

    #!/bin/zsh
    cd /tmp
    cat <<EOF > peco.bug.json
    {
        "CustomFilter": {
            "grep": {
                "Cmd": "grep",
                "Args": ["$QUERY"]
            }
        }
    }
    EOF
    peco --rcfile peco.bug.json --initial-filter grep /proc/meminfo

**Comment by lestrrat** [comment]
@syohex thank you! will close when @rubikitch confirms the issue is fixed

**Comment by rubikitch** [comment]
Works fine! thank you.
