### ISSUE TITLE
v0.3.4 peco_linux_*.tar.gz released aren't zipped

### ISSUE THREAD

**Issue by dan-t** [peco/peco#275]
Hi,

thanks for this nice tool! :)

these are just unzipped tar files so the 'gz' is misleading.
Most likely the zipping was just forgotten.

thanks for this nice tool! :)

Greetings,
Daniel

**Comment by lestrrat** [comment]
@dan-t oversight in the flags, sorry, the files were replaced. thanks for the headsup!
