### ISSUE TITLE
Bug: peco.RotateFilter cause Enter key not work!

### ISSUE THREAD

**Issue by quchunguang** [peco/peco#277]
I mapped peco.RotateFilter to C-m.
When i switched the filter mode and select some line, Enter key works as switch between filter modes instead of end the peco with success.

**Comment by syohex** [comment]
`C-m` is same key as Enter. Similarly`C-i` is same as `TAB`, `C-[` is same as `ESC`. You cannot assign different commands to such keys(`C-m` and `Enter` etc).

https://en.wikipedia.org/wiki/Carriage_return says

> In ASCII and Unicode, the carriage return is defined as 13 (or hexadecimal 0D); it may also be seen as control+M or ^M.

You can know this thing by demo application(`keyboard.go`) of termbox-go. This is screenshot when I type `Enter`.

![demo](https://cloud.githubusercontent.com/assets/554281/10714136/0e6b434c-7b21-11e5-87d1-0de4b33bfa84.png)

**Comment by quchunguang** [comment]
Thanks
