### ISSUE TITLE
--select-1 hang on x64 msdos

### ISSUE THREAD

**Issue by mattn** [peco/peco#279]
https://twitter.com/nitoyon/statuses/660832871863599104

**Comment by syohex** [comment]
I can also reproduce with both released binary and binary which is built from source code.

**Comment by nitoyon** [comment]
It turns out that the hangup occurs on `defer screen.Close()` in `cli.go`.  So, we have to fix termbox-go.

**Comment by nitoyon** [comment]
Fixed & Sending PR https://github.com/nsf/termbox-go/pull/105

**Comment by lestrrat** [comment]
MEMO: need to release peco with updated termbox dep

**Comment by lestrrat** [comment]
I wonder if this has been fixed with v0.3.6?
