### ISSUE TITLE
Bash history with peco

### ISSUE THREAD

**Issue by pragmaticfrank** [peco/peco#280]
Hi,

I was not sure, I should put this here, put here is my favorite use case, so far:

```
# Use peco for history search.
function hp() {
  local action
  # Look up event with peco.
  action="$(history | peco | cut -c 8-)"
  # Store event in history.
  history -s "${action}"
  # Execute.
  eval "${action}"
}
```

This snippet is part of my [history profile](https://gist.github.com/pragmaticfrank/3763dcbbc652370200c9), which I found really useful.

I'm curious, what you think. I would be happy to put this into your README.md as a use case.

**Comment by syohex** [comment]
Please add such utilities to Wiki page.

- https://github.com/peco/peco/wiki
- https://github.com/peco/peco/wiki/Sample-Usage

**Comment by pragmaticfrank** [comment]
Okay, thx I'll. Somehow I've missed the wiki. The README was so rich, I was just going through that.

**Comment by lestrrat** [comment]
Yeah, in this case this probably should be in the wiki.

**Comment by aristipp** [comment]
A great thanks from me!
