### ISSUE TITLE
Unable to read super long line

### ISSUE THREAD

**Issue by tetsutan** [peco/peco#282]
I use peco with zsh-history.
peco can not display old history after I put so long line (maybe about 200kb of json data).
But new lines are displayed. and all lines are displayed after delete long lines from zsh_history.

It means stopping peco when peco find long line, I think.

Is there a sulution?

**Comment by tetsutan** [comment]
Sorry, I solved this issue with `cut` command. But how many characters peco can read by line?

**Comment by lestrrat** [comment]
That's not a peco issue per se, it's a `bufio.Scanner` limitation. See 

* https://golang.org/src/bufio/scan.go#L161
* https://golang.org/src/bufio/scan.go#L71

If the scanner encounters a line that's longer than 64KB, then an error is returned.

**Comment by tetsutan** [comment]
thanks a lot

**Comment by mattn** [comment]
If we resign using of `bufio.Scanner`, and use `bufio.ReadLine` instead, it's possible i guess.
