### ISSUE TITLE
Filename of Windows version

### ISSUE THREAD

**Issue by morinatsu** [peco/peco#285]
After v0.3.3, name of exeutable file was changed 'peco'.
I use v0.3.2 now, it's named 'peco.exe'. 
What happened?

**Comment by syohex** [comment]
f3d87a4b7766e20ad88392b6eab8b352b1deae07 introduces this issue. It make output executable names "peco" for all platforms.

I sent PR #286. Please see.

**Comment by syohex** [comment]
#286 has been merged. Please wait next release.
