### ISSUE TITLE
Error: no buffer to work with was available

### ISSUE THREAD

**Issue by tomohiro1221** [peco/peco#287]
I get an error that tells me no buffer is available. 

In my `~/.zshrc`

```
function peco_select_history() {
  local tac
  (which gtac &> /dev/null && tac="gtac") || \
    (which tac &> /dev/null && tac="tac") || \
    tac="tail -r"
  BUFFER=$(fc -l -n 1 | eval $tac | \
              peco --query "$LBUFFER")
  CURSOR=$#BUFFER # move cursor
  zle -R -c       # refresh
}
```

```
bindkey '^s' peco_select_history
```

I'm using prezto.
I got the above error in iTerm 2 as well as builtin Terminal. 
What could be a cause of this error? I tried restarting iTerm 2, rebooting my computer in vain...

**Comment by syohex** [comment]
Are there any output by `fc -l -n 1 | eval $tac` part ? You can get this message if there are no input. For example `echo -n | peco`.

```
% echo -n | peco
Error: no buffer to work with was available
```

**Comment by tomohiro1221** [comment]
There is no output for `fc -l -n 1 | eval $tac`. It suddenly stopped working without me changing anything. I tried changing `peco_select_history` : 

```
function peco_select_history() {
  BUFFER=$(\history -n -r 1 | peco --query "$LBUFFER")
  CURSOR=$#BUFFER
  zle clear-screen
}
```

Now it's working. Thank you for your time!
