### ISSUE TITLE
ArrowUp/Down/Left/Righ key brake screen

### ISSUE THREAD

**Issue by shakiyam** [peco/peco#290]
When ArrowUp/Down/Left/Right key used and LANG is not ja_JP.UTF-8, search screen is broken.
I think root cause is special characters in internal/keyseq/keys.go's line 134-144.
How about Up/Down/Left/Right, not special characters?

**Comment by lestrrat** [comment]
Do you have a suggestion for replacement characters?

**Comment by shakiyam** [comment]
↑ to Up
↓ to Down
← to Left
→ to Right

**Comment by lestrrat** [comment]
Looks the same to me. At least `hexdump` says they are the same

**Comment by shakiyam** [comment]
I'm sorry to be lacking in my explanation.
My suggestion is to use ASCII characters.

		// Special case for ArrowUp/Down/Left/Right
		switch s {
		case "ArrowUp":
			s = "Up"
		case "ArrowDown":
			s = "Down"
		case "ArrowLeft":
			s = "Left"
		case "ArrowRight":
			s = "Right"
		}

**Comment by lestrrat** [comment]
Ah. OK.
Well, if you got this far, can you please make a PR?

**Comment by lestrrat** [comment]
I'm stupid. I think I can just replace them with `<^>v`
