### ISSUE TITLE
layout is broken when Japanese characters are listed

### ISSUE THREAD

**Issue by bamchoh** [peco/peco#292]
Please see the attached GIF file for the details

![aaa](https://cloud.githubusercontent.com/assets/1514726/14499597/ef40e658-01d9-11e6-8923-38d6a8c20994.gif)

I'm using the version 0.3.5. In my findings, I cannot reproduce this issue with v0.3.0-RC1 binary. But when I rebuilt v0.3.0-RC1 from source code, I can reproduce this issue. When I confirmed the version of rebuilt binary, it's v0.2.12. v0.3.0-RC1 binary from release page was v0.2.11. I guess this issue was coding in between v0.2.11 and v0.3.0-RC1.

**Comment by mattn** [comment]
try to use Raster font.

**Comment by bamchoh** [comment]
It works. Thank you.

**Comment by syohex** [comment]
Can this issue be closed ?
