### ISSUE TITLE
peco flushes filtered items while peco are getting input from pipe

### ISSUE THREAD

**Issue by bamchoh** [peco/peco#293]
I'm afraid I have a foolish question..

When I execute `dir /b /s | peco` under c:\ folder and then type the query `windows`, peco flushes filtered items during end of execution `dir /b /s`. Are there any workaround?

![aaa](https://cloud.githubusercontent.com/assets/1514726/14602248/e1b7e1d2-05a1-11e6-8d49-053b916ff1f3.gif)

**Comment by bamchoh** [comment]
/b がディレクトリ名もしくはファイル名のみ表示するオプション
/s が再帰的に表示するオプション

です。

**Comment by mattn** [comment]
2行ひっかる状態で行が追加されると毎回1件目に移動しちゃうという事で良いですか？

**Comment by bamchoh** [comment]
GIFわかりにくいですね。すいません。
おっしゃられている通り、1件目に戻ってしまうということもそうなのですが、マッチしている一番上の行が動的に変わってしまうので、Enterを押すタイミングによっては意図しないファイル名が取れてしまうというのが本題です。

![aaa](https://cloud.githubusercontent.com/assets/1514726/14609994/0c001b38-05c7-11e6-80a9-41a27e8c8f7b.gif)

**Comment by lestrrat** [comment]
memo:
* User action was allowed to be performed asynchronously wrt to buffer display, but this is apparently affecting UX.
* Maybe we just stop accepting input while display is being updated

**Comment by kawaz** [comment]
I am also well experienced this. 
This problem is likely to occur at a slower or complexity terminal.
Hard to feel the problem in just iTerm2.
Easy to feel the problem in tmux in iTerm2.

**Comment by kawaz** [comment]
Input from the pipe is only appending.
So, if the query is not change, each of the top of the lines of previous filterd and new filtered should be not change.

> Maybe we just stop accepting input while display is being updated

Maybe it is also good.

I think even better that it update only area of the increased line.
If all increased line outside of the screen, there is no need of an update.

**Comment by kawaz** [comment]
I found other behavior due to this problem.
If I press enter (=peco.Finish) while screen flushing, output will be empty.

**Comment by lestrrat** [comment]
which version are you using, just in case?

**Comment by kawaz** [comment]
verry sorry...
I used v0.3.5.
I will confirm again with v0.3.6.

**Comment by kawaz** [comment]
I confirmed with v0.3.6.
This issue exits yet.

But "There are times when output will be empty" is my misunderstanding.
I peco.Finish wthile flushing, output will be random (= which was displayed at the top, during that moment)

**Comment by lestrrat** [comment]
@kawaz so this is separate issue. Please file another issue, so I can keep track.
