### ISSUE TITLE
Support keymap with some conditions

### ISSUE THREAD

**Issue by kawaz** [peco/peco#316]
Normally, I want to map `C-d` to `peco.DeleteForwardChar`.
If the query is empty, I want to map `C-d` to `peco.Cancel`.

Is this possible?

**Comment by lestrrat** [comment]
No, peco does not provide programatic environment, and at least for now, I don't think I plan to do that.
The reason against it is just the sheer complexity that would introduced for it.

**Comment by kawaz** [comment]
I see.
thanks,

**Comment by kawaz** [comment]
I see.
thanks,
