### ISSUE TITLE
Filtering display is slow when working with big buffers

### ISSUE THREAD

**Issue by zchee** [peco/peco#320]
# What is the peco version, OS, architecture? 
sw_vers: (El Capitan Developer Beta 4)
```bash
ProductName:    Mac OS X
ProductVersion: 10.11.6
BuildVersion:   15G24b
```

peco version:
- master: v0.3.6-41cf51ccf6862cf42fea67505afb7f6b6e30efcd
- peco/topic/issue-318: v0.3.6-bdcd74b2eb3f9fe2459f8e107356de3c76c1a0d6

# Abstract
When parses the big buffer, filtering is slower than before version(v0.3.6 stable)

~~Also, **current master** branch(41cf51ccf6862cf42fea67505afb7f6b6e30efcd) have freeze promlem.
but maybe **solved** on https://github.com/peco/peco/pull/319.~~ Thanks.

I took a screencast because that problem is difficult to understand unless movie.
See https://www.youtube.com/watch?v=HDalDyVD7JE

Note: Sorry to bother you, but this screencast is too large because I use the large display.
Recommend is full-screen and 2160p(4k) view quality.

First demo is https://github.com/peco/peco/pull/319 sample.
Second demo uses master branch.
Third(last) demo uses v0.3.6 stable.

===

Filtering zsh history command:
`fc -l -n 1 | tac | ./peco --query "$LBUFFER"` (and bind to `C-q` in zsh)

```
> stat ~/.zsh_history
device  16777220
inode   4274646
mode    33152
nlink   1
uid     501
gid     20
rdev    0
size    4073709
atime   1467273275
mtime   1467273333
ctime   1467273333
blksize 4096
blocks  7960
link
```

# Discussion
I don't know peco source and internal structure, but slow(and deadlock) problem clearly occurs from after the merge https://github.com/peco/peco/pull/304(maybe)
So, I think related `context.Context` and concurrency control.

I think difficult to prepare a huge sample, such as my zsh history, and if you don't have time, I will debug it.
If peco is not intended for parse of huge file, I will give up \o/

Thanks.

**Comment by lestrrat** [comment]
Hmm, the screencast is hard to see...

If you see a deadlock, try sending `kill -ABRT $process_id_for_peco`. This will give you the stracktrace.

**Comment by lestrrat** [comment]
Also, I wasn't sure if you said

1. #319 FIXES the problem, or
2. #319 DOES NOT fix the problem?

**Comment by zchee** [comment]
@lestrrat 
> Hmm, the screencast is hard to see..

Ah, sorry...
I was uploaded raw data to dropbox public, please download https://dl.dropboxusercontent.com/u/145880230/screencast/peco-issues%23320.mp4.
or, I will retake a screencast if you want.

===

> If you see a deadlock, try sending kill -ABRT $process_id_for_peco. This will give you the stracktrace.
> Also, I wasn't sure if you said
> #319 FIXES the problem, or
> #319 DOES NOT fix the problem?

Sorry confusing.
#319 is solved freeze(deadlock) problem. The first and second demo are references for change in #319.

===

This issue main topic is slow filtering.
> BTW, I did not say but peco also have the slow filtering problem.
https://github.com/peco/peco/pull/319#issuecomment-229579521

If use v0.3.6 stable version, filtering is fast.(third demo)
but If use current master, filtering is slow.(second demo)

**Comment by lestrrat** [comment]
Ahhhh, okay. I won't have time tonight, but I'll see what I can do later.

**Comment by zchee** [comment]
@lestrrat Sorry and Thanks 🙇
and issue title is confusing. will edit.

BTW, I'm interesting for how to use `context.Context`. I think peco source code is good references.
I will learn it along with the debug this problem :)

===

> I won't have time tonight, but I'll see what I can do later.

np! prepare for the presentation...?
I wish you the best!

**Comment by lestrrat** [comment]
@zchee hopefully the above PR fixes the issue.
