### ISSUE TITLE
Cannot work CustomFilter in 0.4.0

### ISSUE THREAD

**Issue by rubikitch** [peco/peco#328]
peco-0.4.0 linux-amd64

    {
        "CustomFilter": {
            "egrep1": {
                "Cmd": "grep",
                "Args": ["-Ei", "$QUERY", "test.txt"]
            "egrep2": {
                "Cmd": "grep",
                "Args": ["-Ei", "$QUERY"]
            },
    }

Both works.

    echo abc | peco036 --initial-filter=egrep1
    echo abc | peco036 --initial-filter=egrep2

But these does not work. (no candidates)

    echo abc | peco040 --initial-filter=egrep1
    echo abc | peco040 --initial-filter=egrep2

**Comment by lestrrat** [comment]
fixed by #329
