### ISSUE TITLE
Cannot work SingleKeyJump.ShowPrefix in 0.4.1

### ISSUE THREAD

**Issue by rubikitch** [peco/peco#331]
SingleKeyJump.ShowPrefix works in 0.3.6, but does not in 0.4.1.

    {
        "SingleKeyJump": {
            "ShowPrefix": true
        },
    }

**Comment by lestrrat** [comment]
Note: SingleJumpKeyPrefixes is not being populated

**Comment by lestrrat** [comment]
@rubikitch if you can checkout #332, that would be cool

**Comment by rubikitch** [comment]
Works fine, thanks.
