### ISSUE TITLE
[Question] Can I bind Ctrl-J/K to up/down?

### ISSUE THREAD

**Issue by oscar-broman** [peco/peco#334]
Currently Ctrl-N/P are bound to up/down, but my muscle memory refuses to give in. Is this configurable?

**Comment by syohex** [comment]
See [keymaps](https://github.com/peco/peco#keymaps) section in [README.md](https://github.com/peco/peco/blob/master/README.md)

```json
{
    "Keymap": {
        "C-j": "peco.SelectDown",
        "C-k": "peco.SelectUp"
    }
}
```

**Comment by oscar-broman** [comment]
Ahh alright, perfect. Thanks!
