### ISSUE TITLE
Question: how to abort and send typed characters to stdout

### ISSUE THREAD

**Issue by QiangF** [peco/peco#335]
# What is the peco version, OS, architecture?

Latestes git master branch on Debian Jessie AMD 64.

I have a bash function that displays cheat sheet for all matching files for partial file names in my cheat sheets dir. Fzf helps to find the cheat, but to view the documentation, completed file names doesn't work.

**Comment by lestrrat** [comment]
I didn't quite get your explanation, but from title, I'm guessing you want to, say, type "xyz" to match a path file "foo/bar/xyz", and you only want "xyz" to be output as the result? If that's the case, I must say peco was never really meant for this.

ATM I don't think this will be implemented, but as I said above, I didn't quite understand your explanation. Maybe if you can show us a valid use case and, if it happens to be of general use, we may want to implement it.

**Comment by QiangF** [comment]
I think it happens quite often. For example, you want to rename a file
with the output from peco and change your mind in the middle, abort
the match saves the type. The link to the cheats script I am using is
(https://github.com/lucaswerkmeister/cheats). By default if you type a
cheat command, like "cheat chown", it will list all available cheats
begin with that string, if you have two cheats: "chown a","chown b",
then it will print the doc string of all matching cheats. I think peco
can be used to show the matching cheats dynamically and I want the
ability to view the doc string if I want.

**Comment by lestrrat** [comment]
Can't that be done with the `--null` option?

**Comment by QiangF** [comment]
Iam not sure. How do you type a null character? Does that mean I need to type the same string twice: one before the null character and one after it?
Thank you!

**Comment by QiangF** [comment]
Another use case is for selecting tags to add to a bookmark, if there is no match, peco should return the typed new tag.
There is a project using peco
https://github.com/AndreiUlmeyda/oil
but it lacks the functionality I mentioned.

**Comment by lestrrat** [comment]
So help me out here. I'm having a hard time understanding what exactly you want to do.

"If there is no match"...
so say you have the input
```
A
B
C
```
and you have no match, what is the "typed new tag"?
Hmm, you mean the query that peco receives?

Like,

```
QUERY> foo
A // won't be show, as it does not match
B // ditto
C // ditto
```
then you want to have `foo` printed out?

**Comment by QiangF** [comment]
Exactly. Also there are some other use cases:
https://github.com/junegunn/fzf/issues/1137

**Comment by lestrrat** [comment]
ah! an fzf option!
```
    --print-query         Print query as the first line
```
That makes things significantly easier, as I don't have to dwell on semantics

**Comment by QiangF** [comment]
And it would be nice to have a command to copy the selection to system clipboard, because in the oil script, peco is used inside a function, there is no other way I can copy the selection.

**Comment by lestrrat** [comment]
Meh. Let's do things one at a time...

**Comment by QiangF** [comment]
Sure. fzf also seems to have that functionality (but it is too complicated for my use case). The following is from its documentation:

You can set up key bindings for starting external processes without leaving fzf (execute, execute-silent).

# Press F1 to open the file with less without leaving fzf
# Press CTRL-Y to copy the line to clipboard and aborts fzf (requires pbcopy)
fzf --bind 'f1:execute(less -f {}),ctrl-y:execute-silent(echo {} | pbcopy)+abort'

**Comment by lestrrat** [comment]
I think peco has the ability to execute external commands too (I forget, I don't use it). But seriously, please keep this thread to the original problem :)

**Comment by lestrrat** [comment]
If you are comfortable with Go, you can try the `topic/print-query` branch (https://github.com/peco/peco/tree/topic/print-query) and do:

```
# you may have to install dependencies first via glide
go build cmd/peco/peco.go
whatever input to pass to peco | ./peco --print-query
```

**Comment by QiangF** [comment]
OK. Thank you so much!

**Comment by lestrrat** [comment]
Don't jump the gun :D I'm keeping this open until I actually merge the new feature.
