### ISSUE TITLE
Doesn't work in msys2 on windows 7

### ISSUE THREAD

**Issue by netjune** [peco/peco#336]
Run it, and it did nothing, No output, no prompt.

**Comment by lestrrat** [comment]
Not a windows guy, so I have no clue. @mattn ?

**Comment by mattn** [comment]
AFAIK, peco doesn't work on msys2 or cygwin as long as peco use termbox-go. Windows Console APIs works for cmd.exe not a stdin/stdout/stderr. If you still want to use peco on msys2 or cygwin console though, please try to use [winpty](https://github.com/rprichard/winpty). But I don't make sure.

**Comment by mkielar** [comment]
FYI: 
I was able to run Peco 0.4.7 with Cygwin and [ConsoleZ](https://github.com/cbucher/console#consolez), and it runs ok, except for the fact that I have to manually switch the alternate screen back and forth with `echo`.

Cygwin version: 2.6.1(0.305/5/3)
ConsoleZ version: 1.18.17048
Windows 10: Enterprise & Home.

Here's the full script I used to substitute default bash search:

```
# Run history browser
echo -ne '\033[?47h' # alternate screen
selected_command="$(history | sed -e 's/ *[0-9][0-9]* *//' | sort | uniq -c | sort -k1,1rn -k2 | peco --prompt="→" --query="$READLINE_LINE" --initial-filter=Fuzzy | sed -e 's/ *[0-9[0-9]* *//')"
echo -ne '\033[?47l' # normal screen

# Update command line with selected command	
if [ ! -z "$selected_command" ]; then
	READLINE_LINE="$selected_command"
	READLINE_POINT="$(( $READLINE_POINT + ${#selected_command} ))"
fi
```

**Comment by sergeevabc** [comment]
Windows 7 user here.
I downloaded peco v0.5.11 and launched as follows
```$ fd.exe -t f -d 1 | peco.exe```
Got a list of files which I can select and filter out.
But when I press Enter, nothing happens.
That's why the benefit of Peco remains a mystery to me.
