### ISSUE TITLE
SelectNone, RefreshScreen keep the older selections even after they are removed

### ISSUE THREAD

**Issue by kaushalmodi** [peco/peco#346]
# What is the peco version, OS, architecture? 

- peco version - 0.4.2
- OS - RHEL 6.6
- Terminal - xterm
- Shell - tcsh
- Using in tmux master branch build

# Abstract

- `peco.ToggleSelectionAndSelectNext` correctly selects and unselects a line. But `peco.SelectNone` keeps the older selections on the screen.
- `peco.RefreshScreen` also does not seem to help.

# Discussion

In this gif, 

- you first see that I am selecting some line
- Then I hit `M-g` to call `peco.SelectNone`. But the blue selections still remain.
- When I navigate to those lines, only then the blue selection goes away. So looks like `peco.SelectNone` did actually deselect all the lines, but the older blue highlights still stayed there.
- Then I try calling `peco.SelectAll` (`C-x,h`) -> `peco.SelectNone` (`M-g`) -> `peco.RefreshScreen` ( `F5`). But still nothing happens. You can then see the old blue highlight get removed only when I navigate to those lines.

![peco_select_none_not_working](https://cloud.githubusercontent.com/assets/3578197/18961454/1e1442d2-863b-11e6-8080-bd47ff8c9972.gif)

# My config
- [full config code](https://github.com/kaushalmodi/dotfiles/blob/master/.config/peco/config.json)

**Comment by lestrrat** [comment]
hmm, needs investigation. ETA sometime next week

**Comment by kaushalmodi** [comment]
Thank you! This bug is now fixed for me too.

*But while testing it with `peco.InvertSelection`, I found that that command does not work for me (https://github.com/peco/peco/issues/354).*
