### ISSUE TITLE
[Feature request] Support TOML config?

### ISSUE THREAD

**Issue by kaushalmodi** [peco/peco#347]
# What is the peco version, OS, architecture? 

N/A

# Abstract

Support TOML config as it is easier to use, less picky about commas after last elements, AND we can even add comments in that :)

# Discussion

If `$HOME/.config/peco/config.toml` exists, use that. Else fall back to `$HOME/.config/peco/config.json`.

- [Intro to TOML -- A blog post on what TOML is and how it is better than JSON (and even YAML)](https://npf.io/2014/08/intro-to-toml/)
- [TOML Parser library in Go -- Linking this just in case this is applicable to this feature request](https://github.com/BurntSushi/toml)

**Comment by kaushalmodi** [comment]
I don't know how to code in Go, but [this](https://github.com/spf13/hugo/blob/4d1cb5000312a58bec0c98998f46f14dd6f1e21a/parser/frontmatter.go#L162) is probably where [Hugo - the Go based static website generator](https://github.com/spf13/hugo/blob/4d1cb5000312a58bec0c98998f46f14dd6f1e21a/parser/frontmatter.go#L162) parses its `config.toml` file.

**Comment by lestrrat** [comment]
Do I want to write this? No. Adding more deps for something trivial as a config file is not my priority.
Am I willing to consider merging given a PR? Probably, depending on the quality of PR.

So PRs welcome.

**Comment by kaushalmodi** [comment]
OK, in that case, I will close this issue, because I have 0 knowledge about go.
