### ISSUE TITLE
Textual examples

### ISSUE THREAD

**Issue by JosielSantos** [peco/peco#349]
Hello.
Can you provide textual examples in the readme instead or in alternative to print screens? I am blind and can not see the images.

Thanks in advance.

**Comment by lestrrat** [comment]
Hi, so I'll be honest and admit that I have no clue how this works for you.
What kind of textual example are we talking about here?
Do you mean like a full-paragraph of explanation, or something that involves ASCII art-ish things?

**Comment by JosielSantos** [comment]
Hello.

I use screen readers to interact with the computer, such applications 
speaks for me what you see in the monitor.

A textual example is:

$ cat myFile.txt

This is the content of my file


It is basically copy / past the terminal session into a file or in the 
README.

Or use the 'script' command.


P.S.: I am not want that you do not use printscreen, I want just a way 
for read the examples.
Thank you again.

**Comment by lestrrat** [comment]
Gotcha. I must admit peco is fairly complicated to explain in words, but we'll see what I can do.

**Comment by lestrrat** [comment]
So as an example, does this work?

![Executed `ps -ef | peco`, then the query `root` was typed. This shows all lines containing the word root](http://peco.github.io/images/peco-demo-ps.gif)

**Comment by JosielSantos** [comment]
Great!

This way I and other blind peopple can know what the program does and 
try / practice.


Thanks.
