### ISSUE TITLE
Redisplay bug after updating query (edit, backspace) 

### ISSUE THREAD

**Issue by kaushalmodi** [peco/peco#356]
# What is the peco version, OS, architecture? 

- peco version - 0.4.3+ (built with the latest commit as of today: https://github.com/peco/peco/commit/c29ba5a856b5c498ef1a1f53de3d495fc2902c67 )
- OS - RHEL 6.6
- Terminal - xterm
- Shell - tcsh
- Using in tmux master branch build

# Abstract

The available list of options does not always redisplay as expected. The list of options stays stale after editing the query area.

- Let's say the list has elements `a` and `b`.
- Typing `a` shows `a`
- Backspace.. it still shows `a`.
- Need to then do `C-n`/`C-p`/`C-g`(refresh) to see the correct list

# Discussion

Below GIF shows this issue as I am typing a query, then hitting backspace, modifying the query. You will notice that hitting backspace changes the query, but does not dynamically update the list. You need to `C-n`/`C-p`/`C-g` to refresh the list manually.

![peco_backslash_bug](https://cloud.githubusercontent.com/assets/3578197/19197798/d9b3c180-8c89-11e6-9256-3b0d92029af1.gif)

# My config
- [full config code](https://github.com/kaushalmodi/dotfiles/blob/37e3ed654220a976825ab61d7269c4097cdfb005/peco__config.json)

**Comment by lestrrat** [comment]
Note: This seems to only happen when there's only 1 character in the query, and you delete it.

**Comment by kaushalmodi** [comment]
> This seems to only happen when there's only 1 character in the query

That seemed to be the case.

Thank you for fixing this! I confirm the fix too :)
