### ISSUE TITLE
peco should accept interrupts while reading from stdin (e.g. empty stdin or slow source)

### ISSUE THREAD

**Issue by kawaz** [peco/peco#359]
```
sleep 10 | peco
```

I can't exit with `Ctr+C`, `Ctr+Z`, `Ctr+D`...

**Comment by mattn** [comment]
If I'm an ESP, I'd say you should explain like below. When piped empty stream, peco crash.
```
$ touch empty
$ cat empty | peco
```
![](http://go-gyazo.appspot.com/0dbc1a7ac0310b6f.png)

**Comment by kawaz** [comment]
Sorry, I posted issue in the middle.
I fixed issue.

**Comment by mattn** [comment]
日本語でも構いません。

**Comment by kawaz** [comment]
@mattn がESPしてくれましたが、問題は2つあるようです。

- 一つは空のファイルをパイプで食わせるとエラーで死ぬ問題。
- もう一つは入力が無いけど閉じられても居ないものをパイプで食わせると何の操作も受け付けずに終了できなくなってしまう問題。

僕が時々ハマるのは後者のフリーズする問題です。この場合別プロセスからkillしないと復帰できないので困ります。

**Comment by syohex** [comment]
使用している pecoはバイナリの最新版でしょうか ? もし自分でビルドしている場合, 最新のソース(termbox等の依存を含む)でビルドしなおして再現するか確認いただけないでしょうか ?

**Comment by kawaz** [comment]
Mac でbrew install pecoで入れたバイナリです。

```
$ peco --version
peco version v0.4.3
```

**Comment by kawaz** [comment]
master をビルドしてみましたがやはり再現しますね。

**Comment by lestrrat** [comment]
@kawaz 噂でtermbox-goのバージョンをあげると良いという噂を聞いたので、とりあえず #360 でglide upしてみました。ちょっとやってみてもらえますか？

**Comment by kawaz** [comment]
試してみましたが変わらないようです。

**Comment by lestrrat** [comment]
:/

念のため、新しいバージョンのビルドをしてもらった方法を教えてもらえますか。git pullだけだと駄目で、`glide install`とかされましたでしょうか。

**Comment by kawaz** [comment]
はい、glide ってのを知らなかったのですがdiffのあるファイル名からそれが必要なのかなと思い適当にググって以下のように実行しました。何か足らない手順ありますでしょうか？

```
cd path_to_pecp
git fetch --all
git checkout origin/topic/issue-359
brew install glide
glide install
glide up
go build cmd/peco/peco.go
./cmd/peco/peco.go
```

**Comment by lestrrat** [comment]
`./cmd/peco/peco.go` はきっとタイプですね。`glide up`は余計ですが、別に悪さはしないと思うので大丈夫です。

あとは新しいpecoでのスタックトレースをいただけますか

**Comment by kawaz** [comment]
すみませんスタックトレースってどうやって取るんでしょう…(^^;

**Comment by lestrrat** [comment]
panicになるんですよね？ その結果です。↑上に貼ってもらったヤツと一緒です。
単純に、オリジナルとのこの最新のビルド状態で差があるかどうかも見てみたい感じです

**Comment by kawaz** [comment]
あ、すみません panic ではないです。@mattn のスクショは僕の困っている症状と違います。

`sleep 10 | ./peco` を実行すると↓このような挙動になります。（起動してから何もしてないように見えますがhogehogeとかCtr+CやCtr+Zとか色々入力していますが何も効かないで10秒後にパイプが閉じて終了する）

[![asciicast](https://asciinema.org/a/69jy9nj55x86zs5q3rtqnz7cm.png)](https://asciinema.org/a/69jy9nj55x86zs5q3rtqnz7cm)

**Comment by lestrrat** [comment]
あー、スタックトレース見てなるほど、とか思ってしまった。やっと話がわかった。
`sleep 10 | peco`が10秒待つのは正しいけど、途中で止められないのが問題ってことですね！やっとわかった…

**Comment by kawaz** [comment]
はい、そうです！上手く伝えられなくてすみません。

参考までに閉じていなくても何かしら出力があるパターンをあげておきます。

- `(echo foo; sleep 10) | peco` のように何かしらの出力がある場合は peco は普通に foo の選択とかが動作して、Enterで通常画面に戻れます
- ただし `sleep 10` がまだ生きている間は次のコマンドは打てない状態です
- ですが、pecoからの脱出さえ出来ていれば更に Ctr+C をすることで sleep も殺せて完全に復帰できます


これが何の出力も無いパイプだとpecoからの脱出すらも出来なくて、sleepにCtr+Cシグナルを送ることも出来ず、1コ前のコメントの動画のようにどうしようもなくなります。

**Comment by kawaz** [comment]
↑すみませんURL貼り間違えて同じ動画貼ってしまいました。編集したのでリロードしてください。

**Comment by lestrrat** [comment]
#360 の一番新しいコミット 5ad53b9 でとりあえず読み込みループからは脱出するようになったはずです。確認しえもらえますか

ちなみにですが`sleep 10 | peco`した場合、pecoから脱出できてもsleep 10が生きている間はプロンプトの制御は戻ってこないと思います。この場合はpecoを終了・停止させるとともに、`sleep 10`（もしくはそれと同様の事をしてるプロセス）も終了させないと、すぐには制御は戻ってこないです。そこはpecoがどうこうできる部分ではないので…

**Comment by kawaz** [comment]
`sleep 10 | peco` で `Ctr+C` 他の操作が聞くようになったこと確認しました！
とりあえず何もできなくなる問題はこれで解決しそうです。

pecoから戻ってもsleepが終了しないと制御が戻らない件についてはシェル側の問題だと思うのでコレで良いと思います。ここまで戻れさえすれば更に `Ctr+C` 等で前側のsleepを殺したり出来ますので。

**Comment by kawaz** [comment]
ただ別の問題として、`sleep 10|./peco` の最中に `hoge<Enter>` など適当なクエリ入力をするとpanicするようなので別のissueかもしれませんがとりあえず貼っておきます。

<img width="587" alt="2016-10-22 16 02 53" src="https://cloud.githubusercontent.com/assets/156236/19617688/d2ba1e1c-9871-11e6-820d-640b8607a447.png">

ただし再現は100%ではなく素早く何度か「`sleep 10|./peco` の起動と適当なクエリ入力」を繰り返していると、2,3回に一回再現する程度の再現率でした。

**Comment by lestrrat** [comment]
まぁこれはpanicを安易に使ってる自分が悪いな…

**Comment by lestrrat** [comment]
@kawaz 72b05ec で直るかな？（少なくともpanicは明示的に消したので、それ以外の問題が出なければOK）

**Comment by kawaz** [comment]
再現性が不安定だったので一応20回問題の操作を行ってみましたが、一度も発生しなくなりました。問題なさそうです。それ以外の新しい問題も特に出ていません。

**Comment by lestrrat** [comment]
@syohex @kawaz thank you :)
