### ISSUE TITLE
--select-1 doesn't work

### ISSUE THREAD

**Issue by EMayej** [peco/peco#363]
# What is the peco version, OS, architecture? 

peco version v0.4.4
from homebrew
macOS Sierra 10.12.1

~/.config/peco/config.json
```
{
  "InitialFilter": "SmartCase",
  "Keymap": {
    "C-b": "peco.ScrollPageUp",
    "C-f": "peco.ScrollPageDown",
    "C-g": "peco.Cancel",
    "C-j": "peco.SelectDown",
    "C-k": "peco.SelectUp"
  }
}
```

# Abstract
Run
```shell
echo "foo" | peco --select-1
```

peco doesn't automatically print foo, instead it shows the candidates selecting screen.

**Comment by lestrrat** [comment]
@EMayej Hi, if you know how to build peco from source, can you try building and running #364? Otherwise, don't worry.

**Comment by EMayej** [comment]
@lestrrat Thank you for quick fix. I'll wait for next release.

**Comment by lestrrat** [comment]
no worries. thanks for filing the issue!
