### ISSUE TITLE
peco doesn't take into account any filters that have been input before a source responds

### ISSUE THREAD

**Issue by maoe** [peco/peco#367]
# What is the peco version, OS, architecture? 

* peco v0.4.5
* Linux x86_64 and OS X El Capitan

# Abstract

It would be nice if peco could apply filters that have been input before a source responds.

# Discussion

You can reproduce the issue as follows:

```
% (sleep 5; echo "foo\nbar") | peco
```
Before the `sleep` command returns, input a non-matching filter:
```
QUERY> baz                                                               IgnoreCase [0 (1/1)]
```
When the `sleep` command returns, `peco` thinks there are two matching items:
```
QUERY> baz                                                               IgnoreCase [2 (1/1)]
foo                                                                                          
bar
```
If you type a space, `peco` re-applies the filter and there's no matching item:
```
QUERY> baz                                                               IgnoreCase [0 (1/1)]
```

Could we fix `peco` to respect existing filters even when the source is slow? This happens from time to time when my disk is slow or my machine is overloaded.

**Comment by lestrrat** [comment]
@maoe Can you please check if #368 fixes this issue for you?

**Comment by lestrrat** [comment]
#368 seems to fix this, and I wrote tests for it, so going to merge and close

**Comment by maoe** [comment]
Yes, it did fix the issue. Thanks for the quick turnaround!
