### ISSUE TITLE
Feature: Installation by yum/apt-get

### ISSUE THREAD

**Issue by shigemk2** [peco/peco#375]
# What is the peco version, OS, architecture? 

- Ubuntu 16.10

# Abstract

Mac developers can install peco by brew and Windows developers can install peco by choco, but we cannot install peco either by yum or by apt-get.

Do you have any plan to enable to install peco by Linux package manager?

# Discussion

**Comment by lestrrat** [comment]
I don't plan on releasing any such package. If somebody else would like to do that, they are more than welcome to.

In fact, the core peco developers have nothing to do with `choco` or `homebrew` releases: they are packaged independently.

**Comment by shigemk2** [comment]
> In fact, the core peco developers have nothing to do with choco or homebrew releases

OK, sure. I see. So we can release peco to package manager. Thank you so much!
