### ISSUE TITLE
New feature: --on-cancel

### ISSUE THREAD

**Issue by lestrrat** [peco/peco#381]
# What is the peco version, OS, architecture? 

v0.4.5

# Abstract

I have been reported that pressing `ESC` (and thus cancelling execution) should result in an error, because the next command in the pipeline needs to be able to tell what happened.

In order to do this without breaking backwards compatibility, we should introduce a new command line feature and a configuration parameter

# Discussion

Introduce

```
peco --esc-is-error ...
```
and in config.json

```
{
   "EscIsError": true
}
```

Name of this parameter is not necessarily fixed. Just a tentative placeholder for now

**Comment by mattn** [comment]
`--cancel-is-error` is better? the name `esc` will stick on  something.

**Comment by lestrrat** [comment]
Proposed option: `--on-cancel`.

```
peco --help
....
   --on-cancel        Specify what happens on user canceling the execution ("success" or "error"). Default is "success"
                               for historical reasons. The default value may be changed in future versions.
```

In a config file:

```
{
   "OnCancel": "error"
}
```
