### ISSUE TITLE
--query option couldn't filter correctly for many lines

### ISSUE THREAD

**Issue by nobeans** [peco/peco#389]
# What is the peco version, OS, architecture? 

* peco version v0.4.8
* macOS sierra

# Abstract

The result of filtering using `--query` for many lines option is different for each running.

# Discussion

```
$ for n in {1..100000}; do echo "hoge $n"; done | peco --query hoge
```

The expected status line is

* `IgnoreCase [100000 (1/1389)]`

But actually,

* `IgnoreCase [9179 (1/128)]`
* `IgnoreCase [8531 (1/119)]`
* `IgnoreCase [9457 (1/132)]`

The number of filtered line is different for each running.

When you delete a query string in prompt, the status line expectedly becomes `IgnoreCase [100000 (1/1389)]`.
And then you input `hoge` again in prompt, it expectedly becomes `IgnoreCase [100000 (1/1389)]`.

**Comment by lestrrat** [comment]
I manually bisected and this problem seems to exist on **all** v0.4.x versions.
ATM still have not looked in deep to check out why.

**Comment by lestrrat** [comment]
@nobeans please check `topic/issue-389` branch and 0c06d2c, and see if this fixes your problem.

**Comment by nobeans** [comment]
It seems working well.

**Comment by nobeans** [comment]
Thanks for fixing it so quickly!
