### ISSUE TITLE
[Question] Killing process on exit?

### ISSUE THREAD

**Issue by therockmandolinist** [peco/peco#393]
# What is the peco version, OS, architecture? 

```
peco: v0.4.9
macOS: 10.12.3
```

# Abstract

I was wondering if there's a way to kill processes piped to peco when killing or selecting with peco.

# Discussion

Sometimes I'll run a command (such as an `rg` search for files) in a large directory, and after I choose a file (or just quit peco), rg is still running in the background. This means it takes a while to output my selections, or if I've cancelled, sometimes it takes a second to respond to additional input. Ideally, I'd choose the item, the process would stop, and I'd either immediately regain control of the command line or my selections would be outputted. 

I'm not sure if there's anything peco can do about this, though, just wondering if there's a way around this.

**Comment by lestrrat** [comment]
No, that sounds more like a problem with `rg` or your machine being slow. We just implemented #394 and used `ack ... | peco --exec 'awk ... | xargs less'` to implement search + code browser, but didn't see much slow down.

**Comment by therockmandolinist** [comment]
Ok, thanks for the feedback. Note that by "large directory" I mean on the order of searching most files in home directory, so this is probably not going to be a huge issue anyway.
