### ISSUE TITLE
Piping peco to peco causes crash

### ISSUE THREAD

**Issue by kaushalmodi** [peco/peco#397]
# What is the peco version, OS, architecture? 

- peco 0.4.9 (built from master today using commit 766fdd7)
- RHEL 6.6 64-bit

# Abstract

peco crashed when I piped output of one peco to another.

# Discussion

In an attempt to have peco exit immediately if the result of the command line `--query` arg is just one element ([ref][1]), I tried:

```
echo "a\nb" | peco --query=a | peco --select-1
```

While above use is invalid, it caused peco to crash instead of throwing an error.

Here I expected the first `peco` execution to pass just "a" to the second `peco` instance. The crash ended with

> Error: received signal: interrupt

when I hit *Ctrl C* as I couldn't get out of `peco` otherwise.

[1]: https://github.com/peco/peco/issues/396

**Comment by lestrrat** [comment]
When you say `crash`, you mean there was a stacktrace show?
If that's the case, please use one of the 0.4.8 release files, and please paste the entire stracktrace (NOTE: please DO NOT give me stacktraces from your hand-built binary, as I might want to check against the dependencies' stacktrace I would have no control over if it's your hand-built binary, and I wouldn't know what to do)

If when you say `crash`, there's no stack trace, then it's not a crash. As the error states, the program received a signal, and that really isn't under my control. It's something in your environment.

**Comment by lestrrat** [comment]
Oh wait, this might be a termbox-go related timing issue.

**Comment by kaushalmodi** [comment]
peco 0.4.8 was fine.. but the issue on the master build sounds like a timing issue you mentioned. 

![peco-pipe-bug](https://cloud.githubusercontent.com/assets/3578197/23553034/c4f794fc-ffec-11e6-9435-4fcafa88e11c.gif)

**Comment by lestrrat** [comment]
This one is hard. I'm going to have to see if I can isolate it.

**Comment by lestrrat** [comment]
Well I wrote ab72a55, but somehow I don't think I fixed *everything*. It's bed time for me, so I'm going to sleep on it.
