### ISSUE TITLE
Working with tailed or live input

### ISSUE THREAD

**Issue by CMCDragonkai** [peco/peco#404]
I was looking for an interactive grep like filter (sort of like how wireshark does its filtering) and I just found peco.

So I didn't see this in your examples, but imagine piping the output of tail -f to peco, would peco allow you interactively filter input lines as they come in and you can even interactively change the filter and have the output change accordingly?

In some cases the input lines may need to be stored in a temporary file because the amount logs could grow quite big.

**Comment by lestrrat** [comment]
peco should be able to cope with `tail -f`, but it does not try to be clever with memory usage. it will use up whatever it can, and it will probably run out of internal line IDs at some point.

Just one note: Please don't use the issues as a discussion forum. If you feel that the documentation is lacking on this part, please file an issue to update the document.

**Comment by CMCDragonkai** [comment]
Where is your discussion forum for peco?

**Comment by lestrrat** [comment]
we don't see the need for an official one at the moment. try stackoverflow?
