### ISSUE TITLE
Arm architecture

### ISSUE THREAD

**Issue by azlux** [peco/peco#405]
hi,
On arspberry we are on ARM architecture. Can we have the build for it ?

`
uname -a : `
`
Linux minibian 4.4.26-v7+ #915 SMP Thu Oct 20 17:08:44 BST 2016 armv7l GNU/Linux
`
Thank.
Az

**Comment by lestrrat** [comment]
Yeah, that should be possible.

**Comment by lestrrat** [comment]
@azlux I added rules to build arm builds, too, but I don't think will retrofit the old releases to contain arm builds at this point. For now, please compile it yourself on your environment, or cross-compile it.

```
make build-linux-arm
```

or

```
make build-linux-arm64
```

**Comment by azlux** [comment]
Thank.
It's always a mess for me to compile with go, so I will wait for the next release.
