### ISSUE TITLE
Restore position after --exec

### ISSUE THREAD

**Issue by powerman** [peco/peco#410]
# What is the peco version, OS, architecture? 
Current master, Gentoo Linux, amd64.

# Abstract
In some cases after executing command position of cursor (selection bar) isn't restored correctly.

# Discussion
```
seq 20000 | peco --exec true
```
Next enter `111` as query and try to press `Enter` on elements above and below `3111` (near middle of the screen) - after pressing `Enter` on elements below `3111` cursor jumps to some previous element (usually in top half of screen, i.e. to `3111` or elements before it).

Probably related but a bit different issue is after pressing `Enter` on elements on next page cursor both jumps to `3111` on first page but also became invisible until you'll move it again.

**Comment by lestrrat** [comment]
@powerman Can you try 8069f8e ?

**Comment by powerman** [comment]
Yeah, this helps, thanks!

**Comment by lestrrat** [comment]
@powerman sorry to be pesky, but does that mean the commit *fixed* your problem? (just trying to be sure :)

**Comment by powerman** [comment]
Yes, it fixes my problem. :)

**Comment by lestrrat** [comment]
@powerman thanks! will PR/merge/blah blah blah now.
