### ISSUE TITLE
[Feature Request] Auto scroll

### ISSUE THREAD

**Issue by schef** [peco/peco#420]
It would be cool if there would be option for auto scroll.

Btw. your software helps ALOT!

**Comment by lestrrat** [comment]
> Btw. your software helps ALOT!

Thank you!

---

But please read the guidelines first, and file a new issue with more details and try to explain to us what this will be used for, how it will be displayed, etc.

![image](https://cloud.githubusercontent.com/assets/49281/26294717/d2a6f0a4-3f00-11e7-82cb-c97a28ff4841.png)
