### ISSUE TITLE
Weird characters with ncurses 6.1

### ISSUE THREAD

**Issue by agostonbarna** [peco/peco#446]
# What is the peco version, OS, architecture? 
- peco version v0.5.2 (built with go1.9.2)
- Arch Linux 4.14.20-1-lts, x86_64

# Abstract

After upgrading ncurses to v6.1 weird characters appear on the screen when I try to use peco.

```
$ cat test.txt       
line 1
line 2
line 3
```

```
$ cat test.txt | peco
 �����������������������[%i%p1%dG                            [3 (1/1)]
line 1
line�2�������������������������������
����������������������������������  
line�3��[%i%p1%dG
Waiting for input...
�����������������������������  
```

**Comment by mattn** [comment]
termbox-go (peco uses this for UI libarary) doesn't not use curses library. Please make sure your terminal environment, locale, font, etc...

**Comment by agostonbarna** [comment]
Thanks for the info, but I tested this multiple times and the result is the same:
- run peco with ncurses v6.1 => weird characters
- downgrade ncurses to v6.0 => no weird characters
- upgrade ncurses to v6.1 => weird characters
The two things must be connected somehow.

**Comment by mattn** [comment]
What terminal do you use? I'm not sure, but if your terminal is depend on the curses library, this may be occured.

**Comment by agostonbarna** [comment]
I use Gnome Terminal but also tried Konsole, Terminator, the linux console, and got the same result.

**Comment by mattn** [comment]
Maybe, your terminfo file or environment variables were modified with upgrading ncurses library. termbox-go has some terminal codes which are provided from ncurses5 (but not used as library)

https://github.com/nsf/termbox-go/blob/88b7b944be8bc8d8ec6195fca97c5869ba20f99d/terminfo.go#L39-L40

So please file issue on https://github.com/nsf/termbox-go .

**Comment by agostonbarna** [comment]
Indeed, my terminfo were modified with the upgrade:

infocmp diff:

```diff
4c4
< 	colors#0x100, cols#80, it#8, lines#24, pairs#0x7fff,
---
> 	colors#0x100, cols#80, it#8, lines#24, pairs#0x10000,
39c39
< 	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
---
> 	kind=\E[1;2B, kmous=\E[<, knp=\E[6~, kpp=\E[5~,
44c44
< 	rmcup=\E[?1049l, rmir=\E[4l, rmkx=\E[?1l\E>,
---
> 	rmcup=\E[?1049l\E[23;0;0t, rmir=\E[4l, rmkx=\E[?1l\E>,
51c51
< 	smcup=\E[?1049h, smir=\E[4h, smkx=\E[?1h\E=,
---
> 	smcup=\E[?1049h\E[22;0;0t, smir=\E[4h, smkx=\E[?1h\E=,
```

Thanks for the help, I'll file an issue.

**Comment by mattn** [comment]
Now problem of termbox-go was fixed. Closing. https://github.com/nsf/termbox-go/issues/185
