### ISSUE TITLE
Uim input dialog is located on unexpected place.

### ISSUE THREAD

**Issue by Nobutarou** [peco/peco#450]
#  peco version, OS, architecture
```
# peco --version
peco version v0.5.3 (built with go1.8.3 gccgo (GCC) 7.3.0)
# uname -a
Linux usehage 4.13.16 #2 SMP Thu Feb 15 00:57:00 JST 2018 x86_64 GNU/Linux
# mlterm --version
mlterm version 3.8.4
Features: otl implugin utmp
```

# Abstract
Usually uim input dialog is shown just on the cursor location. But in peco, it is out of terminal. Therefore I cannot see what I am typing in peco.

![out-peco_mlterm](https://user-images.githubusercontent.com/1369439/38040394-65182f24-32ea-11e8-83ae-97a5619bd442.png)
![in-peco_mlterm](https://user-images.githubusercontent.com/1369439/38040393-64da12ac-32ea-11e8-9922-f7ab69218a98.png)
(you can see the uim candidate dialog. But to show the dialog, I have to type space many times and during typing space, I cannot see what I am typing)

I also test urxvt. ln peco, the uim dialog is located on unexpected place, too.

![in-peco_urxvt](https://user-images.githubusercontent.com/1369439/38040830-592899dc-32eb-11e8-9f8f-44263c0d6e4d.png)
![out-peco_urxvt](https://user-images.githubusercontent.com/1369439/38040831-5958cf76-32eb-11e8-82e7-abb0eba509e0.png)

**Comment by lestrrat** [comment]
I have no idea how this works. How does the app specify where the dialogs appear?
@mattn do you  know?

**Comment by mattn** [comment]
@lestrrat Maybe caused by peco does not call termbox.SetCursor(x, y).

**Comment by lestrrat** [comment]
Ah, SetCursor... okay

**Comment by lestrrat** [comment]
@Nobutarou can you check if  #451 works for you?

**Comment by Nobutarou** [comment]
#451 works fine.
ありがとうございます。
![451](https://user-images.githubusercontent.com/1369439/38142216-7859e45a-3476-11e8-8a36-06384a04d23a.png)

**Comment by lestrrat** [comment]
🍺
