### ISSUE TITLE
Not all custom keybindings work properly

### ISSUE THREAD

**Issue by ghost** [peco/peco#459]
### What is the peco version, OS, architecture? 
v0.5.3 (built with go1.10), Subgraph Aaron, Linux amd64

### Abstract

I1m trying to bind PageUp/PageDown, Home/End, Left/Right arrows to a more familiar behavior to me.

Like so:
```
{
	"Prompt":">",
	"Layout":"bottom-up"
}
{
	"Action": {
		"selectAllAndFinish": [
			"peco.SelectAll",
			"peco.Finish"
		]
	},
	"Keymap:" {
		"C-Enter":"selectAllAndFinish",
		"Home":"peco.BeginningOfLine",
		"End":"peco.EndOfLine",
		"Pgup":"peco.ScrollPageUp",
		"Pgdn":"peco.ScrollPageDown",
		"ArrowLeft":"peco.BackwardChar",
		"ArrowRight":"peco.FowardChar"
	}
}
```

Besides Ctrl+Enter, none of the keybindings work as expected. The file above described above was saved as `/home/user/.config/peco/config.json`

**Comment by lestrrat** [comment]
That looks like 2 hashes (`{"Prompt": ....}` and `{"Action":...}`)? If that's verbatim, it should be one hash.
