### ISSUE TITLE
fd makes peco hang in root dir after selection

### ISSUE THREAD

**Issue by Konfekt** [peco/peco#464]
# What is the peco version, OS, architecture? 

peco version v0.5.3 (built with go1.10), OpenSUSE 15.0, 64 bit

# Abstract

In bash or zsh, ONLY in the root dir `/`, the command
```
 fd | peco
```
has to be aborted for the terminal to accept input again after hitting enter.

# Discussion

In bash or zsh, in  the root dir `/`, type
```
 fd | peco
```
search for a term, such as `bin`, and hit enter.
Expected: the selected term appears in the terminal.
What happens instead: The terminal is inaccessible and the command `fd` has to be aborted by `Ctrl+C`.

This does not happen for other grep tools, such as `ag` or `rg`. Again, this issue ONLY occurs in the root dir `/`.

**Comment by lestrrat** [comment]
At first glance, no idea. maybe try finding where peco is getting stuck by 

1. find the pid of peco
2. send an abort signal (`kill -ABRT $pid`)

and send us the entire stacktrace?

**Comment by lestrrat** [comment]
🤔 hmmm... well, let me know if we need to do something with peco.

**Comment by Konfekt** [comment]
Fixed upstream.
