### ISSUE TITLE
Fuzzy could list substring matches first

### ISSUE THREAD

**Issue by abridgett** [peco/peco#478]
# What is the peco version, OS, architecture? 

v0.5.3, Mac

# Abstract

Fuzzy match could list exact/substring matches first

# Discussion

I'm just doing a comparison of various tools like this and thought you might like to know about this one.  When selecting fuzzy matching, some other tools (fzf, skim) list substring matches before the fuzzy matches.  peco doesn't do this (an in fact in my test case they happen to be listed last).  I appreciate that this has a performance impact, however it does mean that people can set fuzzy and get the best of both worlds.

**Comment by lestrrat** [comment]
Hi, thanks for the report.

I just don't use the other tools at all, so inputs like this is always very appreciated. But it also means I don't know what exactly is the expected behavior. Can you please show me a sample input and output that you are expecting so I know I'm at the same wavelength as you?

**Comment by abridgett** [comment]
Sure - ah, in fact it looks like the others aren't doing this either (just happened to on the test case I used then) so this report is completely bogus.  My apologies (feel free to close of course!) 
I had originally wondered if maybe this would be done by making the filter a list, it still seems that the fuzzy matching scoring isn't as good (in either case) as it might be.

Anyhow, searching for "up" (fuzzy) and I was hoping "unpushed" commands to be listed last:
```
QUERY> up                                                                                          Fuzzy [5 (1/1)]
bin/git-unpushed
bin/git-unpushed-stat
bin/git-up
profile/functions.backup
profile/gnupg
```

fzf seemed to have the best matches, but you can see that it's no better here (it was on in some earlier test cases but that must have been luck)
```
> up
  5/38
> bin/git-up
  bin/git-unpushed
  bin/git-unpushed-stat
  profile/gnupg
  profile/functions.backup
```

**Comment by puhitaku** [comment]
@abridgett  I've filed a PR to add `FuzzyLongestSort` flag in the config. It is now merged, and this issue may be closed now or after the versioned binary gets released.
Here's the output of the proposed input and the query `up`:
<img width="402" alt="image" src="https://user-images.githubusercontent.com/2425178/223918662-093e19e8-dab8-41cd-9553-b1bcebca31b0.png">

**Comment by puhitaku** [comment]
@lestrrat Thanks for releasing the latest version. The request is fulfilled now I guess, while the author is not responding. Could you close here?

**Comment by lestrrat** [comment]
@puhitaku thanks for your contribution. much appreciated!
