### ISSUE TITLE
No binaries for latest release

### ISSUE THREAD

**Issue by RiaanBurger** [peco/peco#493]
# What is the peco version, OS, architecture?

peco v0.5.5

# Abstract

There are no compiled binaries in the latest artefact for the GitHub release.

# Discussion

The release tagged as latest, currently v0.5.5 as presented on [github.com/peco/peco/releases](https://github.com/peco/peco/releases) does not have any compiled binaries.

In our case is presented as a problem when all our desktops, managed by ansible, failed on the peco role.

**Comment by lestrrat** [comment]
release process botch, I guess. oops

**Comment by lestrrat** [comment]
I think it went through properly this time around with v0.5.6.

**Comment by RiaanBurger** [comment]
Ansible report:

```
...
TASK [cli/peco : Import | Install | Download] ******************************************
changed: [localhost]
...
```

`peco --version`

`peco version v0.5.6 (built with go1.13)`

Works perfectly, thank you very much.
