### ISSUE TITLE
Can't query multiple characters with continuous input from pipe

### ISSUE THREAD

**Issue by kawaz** [peco/peco#494]
# What is the peco version, OS, architecture? 

OS: macOS Catalina 10.15.2
peco: v0.5.6 

# Abstract
Only the first character is queried in cases where the input gradually increases from the pipe while peco is running.

# Discussion
The problem can be easily reproduced by doing the following:

```bash
while :; do echo $RANDOM; sleep 0.1; done | peco
```

- v0.5.6: For example I can not query "12".
- v0.5.3: No ploblem. I can query "12".
- v0.5.6 reverted #491: No ploblem. I can query "12".

**Comment by lestrrat** [comment]
Thanks. Let me take a look...

**Comment by lestrrat** [comment]
We have unintentionally uncovered a synchronization problem, one which I have suspicions but no definite candidate. Investigating....

**Comment by lestrrat** [comment]
Alright, I'm starting to understand where the problem lies, and I'm going to need to think about this one for a bit.

**Comment by lestrrat** [comment]
@kawaz can you try testing with #495 and see if it solves your issues?

**Comment by kawaz** [comment]
@lestrrat Great! My problem has been resolved.
It seemed to be a hard work, but I was surprised that the solution was super fast.

**Comment by lestrrat** [comment]
Cool! Thanks for the report!

merged #495 (but it didn't auto-close this issue... :/) . Closing.
