### ISSUE TITLE
Fixing TOC in README.md

### ISSUE THREAD

**Issue by sarisia** [peco/peco#507]
# What is the peco version, OS, architecture? 

N/A

# Abstract

PR #504 introduces GitHub Actions to update TOC in README.md automatically,
but it's not working well and now we do not have TOC.

I've looked into it, and found it's the problem with [thlorenz/doctoc](https://github.com/thlorenz/doctoc), which is used by
[technote-space/toc-generator](https://github.com/technote-space/toc-generator) action in toc.yml.

# Discussion

I've submitted a PR for thlorenz/doctoc#183, but because of doctoc seems not being maintained
for over a year, I'm not sure when will this get merged.

So, in the meanwhile, I want to fix our README.md by:
1. patch technote-space/toc-generator to use patched doctoc ([neuenmuller/doctoc](https://github.com/neuenmuller/doctoc/tree/entire))
2. use toc-generator action patched above in toc.yml in this project

I'd like to confirm that:
* is this approach ok to proceed?
* are there any approaches better than this?

**Comment by lestrrat** [comment]
I think it's totally fine. I can think of a couple of other workarounds, but as long as it works, I'm game.
