### ISSUE TITLE
When type C-a, cursor move to beginning at line ignore the prompt. and cursor become two.

### ISSUE THREAD

**Issue by yoooz** [peco/peco#512]
# What is the peco version, OS, architecture? 
peco version is v0.5.8
OS is macOS Catalina 10.15.7
My terminal environments are below.
- iTerm 3.3.12
- tmux 3.1b
- zsh 5.7.1

# Abstract
When type C-a to moving cursor to line of beginning after typing some characters, cursor move to beginning at line ignore the prompt.
And cursor become two.

Even if this happens, there is no problem to typing keywords and move curosr.
But  there is a sense of discomfort.

Is there any way to fix it?

![画面収録 2020-10-23 2 15 04 mov](https://user-images.githubusercontent.com/54015757/96907326-0c7ce280-14d6-11eb-900b-164cc9ca2841.gif)

**Comment by mattn** [comment]
I can reproduce this.
![screenshot](https://user-images.githubusercontent.com/10111/96909179-a2197180-14d8-11eb-8487-15cf7a536f18.gif)

**Comment by syohex** [comment]
It looks a following can fix this issue. However I'm not sure it is correct.

```diff
diff --git a/layout.go b/layout.go
index 4c1d68a..8cd6da6 100644
--- a/layout.go
+++ b/layout.go
@@ -160,7 +160,7 @@ func (u UserPrompt) Draw(state *Peco) {
 			Fill: false,
 		})
 	default:
-		posX = c.Pos()
+		posX = c.Pos() + u.promptLen + 1
 		// the caret is in the middle of the string
 		prev := int(0)
 		var i int
```

**Comment by yoooz** [comment]
Thanks!
Fixing layout.go as mensioned above, so cursor move expected.
I think this fix should be incorporated.

Can i create a PR for this issue?

**Comment by syohex** [comment]
I have sent PR #513

**Comment by lestrrat** [comment]
thanks, merged. I'm about to step out now, I'll do releng when I get a chance
