### ISSUE TITLE
Update choco package to 0.5.8

### ISSUE THREAD

**Issue by musm** [peco/peco#517]
https://chocolatey.org/packages/peco#versionhistory is still at 0.5.7

**Comment by laurentkempe** [comment]
@musm I created a PR for it on https://github.com/taichi/chocolatey-peco/pull/7
now we have to wait that @taichi merge it and push the chocolatey package

**Comment by laurentkempe** [comment]
This is now available on https://chocolatey.org/packages/peco/0.5.8 and this issue can be closed!

**Comment by syohex** [comment]
Thanks @laurentkempe 👍
