### ISSUE TITLE
Add option to only output queried line, without including the line index

### ISSUE THREAD

**Issue by SidnerMagneli** [peco/peco#522]
peco version v0.5.8 (built with go1.15.5)
Mac OS Big Sur
Intel 

# Abstract
When running peco with the --exec option, the whole line, including the index, gets passed to stdout which prevent's execution of commands.

# Discussion
I use peco to search my terminal history. It would be very useful one could directly execute a queried line. The problem is that as of now, the line index gets passed along with the line which breaks most commands. It would be cool if you could only pass the line and not the index. This it what currently happens when i want to execute a command from history.

> history | peco --exec zsh
> => zsh: command not found: 2212
> => Error: failed to execute command: exit status 127

**Comment by lestrrat** [comment]
Untested, but something like this will not work for your use case?

```
history | peco | sed -E  's/^[0-9]+ +//' | zsh
```

**Comment by lestrrat** [comment]
Cool. Will close, but just for explanation...

The main point with implementing something that filters output within peco is that you need to make a choice between 
1) specific feature to exclude line numbers
2) general feature to modify the output of peco

1 is not *that* hard, but it's a risk in that we run the risk of adding more and more similar features (e.g. remove another pattern of prefixes, remove line numbers but in a different format, etc)

2 is... well, you need to come up with an efficient and generic solution, which isn't exactly easy. I don't think this *particular* use case warrants a big change.
