### ISSUE TITLE
System-wide configuration

### ISSUE THREAD

**Issue by DarkPark** [peco/peco#531]
Many programs have their congins in /etc and some additional configuration in the user dir e.g. /home/user/.config/...
At the moment peco seems does not check /etc/peco/config.json file but it would be great to implement this behavior.

**Comment by lestrrat** [comment]
peco doesn't merge configuration files, so I'm not sure how useful looking up a system-wide configuration file would be. E.g., fundamentally it wouldn't be any different from `alias peco="/path/to/peco --config=/etc/peco/config.json"`?

**Comment by DarkPark** [comment]
Yes, I've figured it out the same way. But maybe it's better to be able to merge global and local pieces of config?

**Comment by lestrrat** [comment]
Personally, that falls into "PRs welcome!" category :)

Closing for now, but please feel free to reopen if you want to discuss further
