### ISSUE TITLE
using Peco in HTOP or NTOP

### ISSUE THREAD

**Issue by azinsharaf** [peco/peco#533]
# What is the peco version, OS, architecture? 
v0.5.10, windows 10

# Abstract
Hi, Can we use `peco` in task manager CLI applications like `htop` or `ntop` to filter the processes? It doesn't work on my machine.

**Comment by syohex** [comment]
Those programs are interactive programs and use a lot of escape sequences for drawing, so I think that it is difficult to use those output as the input of other programs like `peco`, `grep` etc.

https://stackoverflow.com/a/17551928

`htop` author said as above link.

**Comment by azinsharaf** [comment]
thanks for clarification.
