### ISSUE TITLE
panic: runtime error on kitty

### ISSUE THREAD

**Issue by ngc-bg** [peco/peco#535]
# What is the peco version, OS, architecture? 
peco version v0.5.10 (built with go1.18.1) on ArcoLionux 5.18.1-arch1-1 x86_64

# Abstract
Using peco according the examples eg. _ps -aux | peco_ leads to *panic: runtime error: index out of range [5] with length 0* 

panic: runtime error: index out of range [5] with length 0

goroutine 42 [running]:`
github.com/nsf/termbox-go.send_attr(0x1804?, 0x0?)
	github.com/nsf/termbox-go@v0.0.0-20190817171036-93860e161317/termbox.go:162 +0x339
github.com/nsf/termbox-go.send_clear()
	github.com/nsf/termbox-go@v0.0.0-20190817171036-93860e161317/termbox.go:248 +0x2b
github.com/nsf/termbox-go.update_size_maybe()
	github.com/nsf/termbox-go@v0.0.0-20190817171036-93860e161317/termbox.go:272 +0x151
github.com/nsf/termbox-go.Flush()
	github.com/nsf/termbox-go@v0.0.0-20190817171036-93860e161317/api.go:165 +0x33
github.com/peco/peco.(*Termbox).Flush(0x562d33547d98?)
	github.com/peco/peco/screen.go:52 +0x85
github.com/peco/peco.(*StatusBar).PrintStatus(0xc0001a6120, {0x562d33547d85, 0x14}, 0x0)
	github.com/peco/peco/layout.go:279 +0x3c9
github.com/peco/peco.(*View).printStatus(0xc0001940a8, {0x562d335b94c0?, 0xc0001a6020?}, {0x7ffac77b1868, 0xc000194030})
	github.com/peco/peco/view.go:74 +0xc9
github.com/peco/peco.(*View).Loop(0xc0001940a8, {0x562d335b9710, 0xc000118c40}, 0x0?)
	github.com/peco/peco/view.go:50 +0x227
created by github.com/peco/peco.(*Peco).Run.func4
	github.com/peco/peco/peco.go:369 +0x27a

The behavior is as expected with urxvt and xterm - everything is working as it should.

**Comment by syohex** [comment]
Cloud you show us the output of `ps -aux` that crashes peco ?

**Comment by sisisin** [comment]
This error occurred on my macOS machine, too.
But it seems to occor only on tmux terminal. And iTerm2,terminal.app do not.

### env

- peco version v0.5.10 (built with go1.17.2)
- macOS 12.3.1 Apple M1 Max
- tmux 3.3a

```
% echo foo | peco
panic: runtime error: index out of range [2] with length 0

goroutine 18 [running]:
github.com/nsf/termbox-go.SetCursor(0x7, 0x0)
        github.com/nsf/termbox-go@v0.0.0-20190817171036-93860e161317/api.go:214 +0x178
github.com/peco/peco.(*Termbox).SetCursor(0x1400000c0d8, 0x7, 0x0)
        github.com/peco/peco/screen.go:38 +0x30
github.com/peco/peco.UserPrompt.Draw({0x140000607c0, {0x104bd0684, 0x6}, 0x6, 0x1400007984a}, 0x14000079500)
        github.com/peco/peco/layout.go:189 +0x4d4
github.com/peco/peco.(*BasicLayout).DrawPrompt(...)
        github.com/peco/peco/layout.go:672
github.com/peco/peco.(*BasicLayout).DrawScreen(0x1400000c630, 0x14000079500, 0x0)
        github.com/peco/peco/layout.go:688 +0xa0
github.com/peco/peco.(*View).drawScreen(0x1400000c648, {0x104c406b8, 0x14000060720}, 0x0)
        github.com/peco/peco/view.go:86 +0x70
github.com/peco/peco.(*View).Loop(0x1400000c648, {0x104c41098, 0x14000102c40}, 0x1400000c588)
        github.com/peco/peco/view.go:66 +0x390
created by github.com/peco/peco.(*Peco).Run.func4
        github.com/peco/peco/peco.go:369 +0x1bc
```

**Comment by ngc-bg** [comment]
Oddly enough I am not able to reproduce it currently. Still, my default $TERM is  xterm-kitty and it was not changed. Tmux + kitty on the other hand:

echo $TERM
tmux-256color
~> ps -aux | peco
panic: runtime error: index out of range [5] with length 0

goroutine 18 [running]:
github.com/nsf/termbox-go.send_attr(0x1790?, 0x0?)
        github.com/nsf/termbox-go@v0.0.0-20190817171036-93860e161317/termbox.go:162 +0x339
github.com/nsf/termbox-go.send_clear()
        github.com/nsf/termbox-go@v0.0.0-20190817171036-93860e161317/termbox.go:248 +0x2b
github.com/nsf/termbox-go.update_size_maybe()
        github.com/nsf/termbox-go@v0.0.0-20190817171036-93860e161317/termbox.go:272 +0x151
github.com/nsf/termbox-go.Flush()
        github.com/nsf/termbox-go@v0.0.0-20190817171036-93860e161317/api.go:165 +0x33
github.com/peco/peco.(*Termbox).Flush(0x562507138d98?)
        github.com/peco/peco/screen.go:52 +0x85
github.com/peco/peco.(*StatusBar).PrintStatus(0xc000074820, {0x562507138d85, 0x14}, 0x0)
        github.com/peco/peco/layout.go:279 +0x3c9
github.com/peco/peco.(*View).printStatus(0xc00000c648, {0x5625071aa4c0?, 0xc000074720?}, {0x7f7a575370e8, 0xc00000c5d0})
        github.com/peco/peco/view.go:74 +0xc9
github.com/peco/peco.(*View).Loop(0xc00000c648, {0x5625071aa710, 0xc00011ac40}, 0x0?)
        github.com/peco/peco/view.go:50 +0x227
created by github.com/peco/peco.(*Peco).Run.func4
        github.com/peco/peco/peco.go:369 +0x27a

In same time on urxvt:
echo $TERM
tmux-256color
~> ps -aux | peco

No issues at all.

**Comment by syohex** [comment]
@ngc-bg Could you unset `TERMINFO` environment variable and check to reproduce ?

**Comment by ngc-bg** [comment]
> @ngc-bg Could you unset `TERMINFO` environment variable and check to reproduce ?

Cannot reproduce it that way! Like you suggested:
```
kitty -> 
> echo $TERMINFO
> /usr/lib/kitty/terminfo
> export TERMINFO=
> ps -aux | peco

```
working as it should. Thank you for looking on the issue...cheers!
