### ISSUE TITLE
HELP: How to remove a default keybind ?

### ISSUE THREAD

**Issue by animalsThink** [peco/peco#537]
# What is the peco version, OS, architecture? 
$peco  --version
peco version v0.5.10 (built with go1.16)
$ uname -a
Linux  5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# Abstract
I'd like to remove C-Space keybinding.

# Discussion
The below config.json adds M-Space keybinding successfully. But C-Space still does the same action.
{
    "Keymap": {
        "M-Space": "peco.ToggleSelectionAndSelectNext"
    }
}

I don't need the default C-Space keybinding anymore, and tried to remove it.                                                   
{
    "Keymap": {
        "M-Space": "peco.ToggleSelectionAndSelectNext",
        "C-Space": ""
    }
}

{
    "Keymap": {
        "M-Space": "peco.ToggleSelectionAndSelectNext",
        "C-Space": null
    }
}

Both cases failed printing an error message shown below: 
Error: failed to setup peco: failed to apply configuration: failed to populate keymap: failed to apply key bindings: failed to 
resolve action name : could not resolve : no such action
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe

Are there any way to remove default keybindings?

**Comment by lestrrat** [comment]
IIRC, try `"C-Space": "-"`?

**Comment by animalsThink** [comment]
> IIRC, try `"C-Space": "-"`?

Thank you, lestrrat!
It worked perfectly.

**Comment by lestrrat** [comment]
:+1:

**Comment by animalsThink** [comment]
> 👍

{
    "Action": {
        "foo.Null": [
            "peco.SelectDown",
            "peco.SelectUp"
        ]
    },
    "Keymap": {
        "M-Space": "peco.ToggleSelectionAndSelectNext",
        "C-Space": "foo.Null"
    }
}

Sorry, I mistakenly used a wrong config file.
The above is what I write in vim and it worked. When I rechecked here, I found your  reply and changed the file but forgot to save it before checking whether the problem is solved.
Actually "-" stopped emitting an error but C-Space still does the default action.

**Comment by lestrrat** [comment]
I tried it on my machine, and I can't reproduce.
This slightly modified version works for me

```
{
  "Action": {
    "foo.Null": [
      "peco.SelectUp"
    ]
  },
  "Keymap":{
    "C-Space": "foo.Null"
  }
}
```

**Comment by animalsThink** [comment]
Thank you for taking your time to reply.
I think simpler is better. SelectUp action is harmless enough.
(I wanted to remove C-Space keybinding because I use C-Space to trigger linux input method editor to input Japanese.)

**Comment by lestrrat** [comment]
@animalsThink I'm not sure I follow. "C-Space":"-" also works for me (i.e. it does nothing).

**Comment by animalsThink** [comment]
> @animalsThink I'm not sure I follow. "C-Space":"-" also works for me (i.e. it does nothing).

I rechecked and "-" worked...
I am sorry for causing trouble out of nothing and taking your time.
I thank you again for your kindness and patience.
